name: Build and deploy docs (docs.freeunit.org)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - prod
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  call-docs-build-push:
    uses: freeunitorg/docs/.github/workflows/docs-build-push.yml@main
    permissions:
      pull-requests: write
      contents: read
      pages: write
      id-token: write
    with:
      production_url_path: ""
      preview_url_path: "/previews/docs"
      docs_source_path: "deploy"
      docs_build_path: "."
      doc_type: "sphinx"
      environment: ${{ inputs.environment }}
      auto_deploy_branch: "main"
      auto_deploy_env: "prod"